[unix_http_server]
file=%(ENV_PROJECT_ROOT)s/var/run/supervisor.sock   ; (the path to the socket file)

[supervisord]
logfile=%(ENV_PROJECT_ROOT)s/var/log/supervisord.log   ; (the path to the log file)
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=%(ENV_PROJECT_ROOT)s/var/run/supervisord.pid   ; (the path to the PID file)
minfds=1024
minprocs=200

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix://%(ENV_PROJECT_ROOT)s/var/run/supervisor.sock

[include]
files = %(ENV_PROJECT_ROOT)s/startup/supervisord/conf.d/*.conf

