RECAPTCHA_SECRET_KEY: "6LfaQZcqAAAAAHVGcoSAw4Dcy2ijsXNn7J4OwcnH"
APP_ROOT: /tinker
MAIL_SERVER: mail.mimuw.edu.pl
MAIL_PORT: 587
MAIL_USERNAME: magnetstein
MAIL_PASSWORD: '$AjzRRPVXb3SW&u2DHGWN7t6'
MAIL_USE_TLS: True
MAIL_DEFAULT_SENDER: tinker@mimuw.edu.pl
