# syntax=docker/dockerfile:1.3
FROM node:18 as build-stage
WORKDIR /web
COPY ./web/ /web/
RUN --mount=type=cache,target=/web/node_modules npm install && npm run build

FROM nginx:1.24.0
COPY --from=build-stage /web/build/ /code/web/build/
COPY nginx-prod.conf /etc/nginx/conf.d/default.conf