# syntax=docker/dockerfile:1.3
FROM node:22 as build-stage

VOLUME /web/node_modules
WORKDIR /web
COPY ./web/ /web/

RUN npm install && npm run build

FROM nginx:1.24.0
COPY --from=build-stage /web/dist/ /code/web/dist/
COPY startup/nginx-prod.conf /etc/nginx/conf.d/default.conf
