    types_hash_max_size 2048;

    upstream python {
        server 127.0.0.1:5000;
    }

    upstream web {
        server 127.0.0.1:3000;
    }

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    server {
        server_name localhost;
        root /usr/share/nginx/html;
        listen 8000;
        client_max_body_size 128M;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        location ~ ^/(tinker/(?:socket[.]io|api))(/.*)? {
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_pass http://python/$1$2$is_args$args;
        }
        location ~ ^/tinker($|/.*) {
            proxy_set_header Accept-Encoding "";
            rewrite /tinker/ws$ /tinker/ws/ break;
            proxy_pass http://web;
        }
        location / {
            absolute_redirect off;
            rewrite (.*) /tinker$1 redirect;
        }
    }

