[program:celery]
command=./env.sh exec celery --app app.celery worker -P eventlet --loglevel=info --logfile=%(ENV_PROJECT_ROOT)s/var/log/celery.log
directory=%(ENV_PROJECT_ROOT)s
autostart=false
autorestart=true
stderr_logfile=%(ENV_PROJECT_ROOT)s/var/log/celery-error.log
stdout_logfile=%(ENV_PROJECT_ROOT)s/var/log/celery-access.log

