[program:redis]
command=redis-server
directory=%(ENV_PROJECT_ROOT)s
autostart=false
autorestart=true
stderr_logfile=%(ENV_PROJECT_ROOT)s/var/log/redis-error.log
stdout_logfile=%(ENV_PROJECT_ROOT)s/var/log/redis-access.log

