"""empty message

Revision ID: fb9e6fdda6d6
Revises: e83fdec3b0c9
Create Date: 2026-05-23 05:40:40.426825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb9e6fdda6d6'
down_revision = 'e83fdec3b0c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'filename')
    )
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_set_filename'), ['filename'], unique=False)

    op.create_table('data_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['data_set.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'filename')
    )
    with op.batch_alter_table('data_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_file_filename'), ['filename'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_file_filename'))

    op.drop_table('data_file')
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_set_filename'))

    op.drop_table('data_set')
    # ### end Alembic commands ###
